envVarGroups:
  - name: shared-credentials
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chama_o_sindico
          property: connectionString
      - key: KAFKA_SERVICE_URI
        value: "" 
    secretFiles:
      - key: service.key
        mountPath: /etc/secrets/service.key
      - key: service.cert
        mountPath: /etc/secrets/service.cert
      - key: ca.pem
        mountPath: /etc/secrets/ca.pem

services:
  - type: web
    name: server
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "node dist/main.js"
    healthCheck:
      path: /api
      initialDelaySeconds: 30
    envVarGroups:
      - name: shared-credentials

  - type: worker
    name: sindico-consumer
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "node dist/consumer.js"
    envVarGroups:
      - name: shared-credentials