# render.yaml (Versão com indentação e estrutura 100% corrigidas)

# O bloco 'services' é o único item no nível raiz do arquivo.
services:
  # O hífen (-) indica o início de um novo item na lista de serviços.
  # Serviço da API REST (seu serviço "server")
  - type: web
    name: server
    env: node
    plan: free
    buildCommand: 'npm install && npm run build'
    startCommand: 'node dist/main.js'
    # 'healthCheck' está corretamente aninhado sob o serviço.
    healthCheck:
      path: /api
      initialDelaySeconds: 45
    # 'envVars' também está aninhado sob o serviço.
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chama_o_sindico # Nome do seu serviço de banco de dados no Render
          property: connectionString
      - key: KAFKA_SERVICE_URI
        fromSecret: KAFKA_SERVICE_URI
      - key: NODE_ENV
        value: production
    # 'secretFiles' também está aninhado sob o serviço.
    secretFiles:
      - key: service.key
        mountPath: /etc/secrets/service.key
      - key: service.cert
        mountPath: /etc/secrets/service.cert
      - key: ca.pem
        mountPath: /etc/secrets/ca.pem

  # Serviço do Consumer (Background Worker)
  - type: worker
    name: sindico-consumer
    env: node
    plan: free
    buildCommand: 'npm install && npm run build'
    startCommand: 'node dist/consumer.js'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chama_o_sindico
          property: connectionString
      - key: KAFKA_SERVICE_URI
        fromSecret: KAFKA_SERVICE_URI
      - key: NODE_ENV
        value: production
    secretFiles:
      - key: service.key
        mountPath: /etc/secrets/service.key
      - key: service.cert
        mountPath: /etc/secrets/service.cert
      - key: ca.pem
        mountPath: /etc/secrets/ca.pem
